export const ROUTES = {
  HOME: '/',
  SHOP: '/dyqani',
  PRODUCT: (slug: string) => `/produkt/${slug}`,
  PRODUCT_PARAM: '/produkt/:slug',
  COLLECTIONS: '/koleksionet',
  MUSIC: '/muzika',
  CONCERTS: '/koncertet',
  ABOUT: '/rreth-nesh',
  CART: '/shporta',
  CHECKOUT: '/checkout',
  ORDER_CONFIRMATION: (id: string) => `/porosi-konfirmuar/${id}`,
  ORDER_CONFIRMATION_PARAM: '/porosi-konfirmuar/:id',
  WISHLIST: '/listat-e-deshirave',
  LOGIN: '/hyrja',
  REGISTER: '/regjistrohu',
  FORGOT_PASSWORD: '/fjalekalim-i-harruar',
  ACCOUNT: '/llogaria',
  ACCOUNT_ORDERS: '/llogaria/porositë',
  ACCOUNT_ORDER_PARAM: '/llogaria/porosi/:id',
  ACCOUNT_PROFILE: '/llogaria/profili',
  ACCOUNT_ADDRESSES: '/llogaria/adresat',
  ACCOUNT_SETTINGS: '/llogaria/cilesimet',
  ADMIN: '/admin',
  ADMIN_PRODUCTS: '/admin/produktet',
  ADMIN_PRODUCT_ADD: '/admin/shto-produkt',
  ADMIN_PRODUCT_EDIT_PARAM: '/admin/ndrysho-produkt/:id',
  ADMIN_ORDERS: '/admin/porositë',
  ADMIN_CUSTOMERS: '/admin/klientët',
  ADMIN_ANALYTICS: '/admin/analitika',
  ADMIN_SETTINGS: '/admin/cilesimet',
  ADMIN_CATEGORIES: '/admin/kategoritë',
  ADMIN_DISCOUNTS: '/admin/zbritjet',
  ADMIN_REVIEWS: '/admin/vlerësimet',
  ADMIN_INVENTORY: '/admin/inventari',
  CONTACT: '/kontakt',
  FAQ: '/faq',
  SHIPPING: '/dergesa',
  RETURNS: '/kthimet',
  SIZE_GUIDE: '/udhezuesi-i-madhesive',
  PRIVACY: '/privatesia',
  TERMS: '/kushtet',
} as const;
